services:
  db:
    image: mongo:8
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: music-video-guidance
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - "./seeds:/docker-entrypoint-initdb.d:ro"
