db.musics.insertMany([
  {
    title: "Despacito",
    artist: "Luis Fonsi ft.Daddy Yankee",
    views: 8890489896,
    duration: 281,
    date: "13/01/2017",
    url: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    description: "Some people dancing bachata style in an town in Latin America",
    rating: "None",
    content: [],
    notes: "",
    isAgeRestricted: false,
    safeAlternative: "",
  },
  {
    title: "Marvin Gaye",
    artist: "Charlie Puth ft. Meghan Trainor",
    views: 761194354,
    duration: 208,
    date: "1/04/2015",
    url: "https://www.youtube.com/watch?v=igNVdlXhKcI",
    description: "A boring prom gets exciting",
    rating: "Moderate",
    content: ["Couples are making out", "A couple gets into a car", "A couple goes in to the janitor room", "Couples are lyingdown on the floor and making out", "The bottom of the bathroom door gap is show in which 3 people are standing and a bra falls of", "2 faculty members are making out in the bathroom stall" ],
    notes: "",
    isAgeRestricted: false,
    safeAlternative: "",
  },
])
